// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoOD6O7xfE-VIv_L4EQyH_aQYh7wDIYkw',
    appId: '1:161862354786:android:67a1d5c99d27a5a0e73a2e',
    messagingSenderId: '161862354786',
    projectId: 'uni-food-flutter',
    databaseURL: 'https://uni-food-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uni-food-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoOD6O7xfE-VIv_L4EQyH_aQYh7wDIYkw',
    appId: '1:161862354786:ios:67a1d5c99d27a5a0e73a2e',
    messagingSenderId: '161862354786',
    projectId: 'uni-food-flutter',
    databaseURL: 'https://uni-food-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uni-food-flutter.firebasestorage.app',
    iosBundleId: 'com.example.unifood',
  );
}

